### ISSUE TITLE
Ajout de la date dans le descriptif du batch

### ISSUE THREAD

**Issue by fredblain** [haum/haumtalks#14]
@jblb fait remarquer que les dates des confs ne sont pas mentionnées sur les pages de ces dernières (uniquement sur la page d'accueil de talks.haum.org qui liste les conférences).

Je ne pensais pas ça gênant mais ça semble l'être, et il est vrai que ça semble plus logique que ce soit aussi affiché, d'autant plus quand on communique le lien direct vers la conf (via Twitter par ex).

**Comment by Matael** [comment]
C'est fait avec la nouvelle page. Je ferme ça.
